import Head from "next/head";
import { PostSummary } from "../types";
import { fetchNotionPageList } from "../services/notionApi";
import { convertNotionPageListToPostSummaryList } from "../utils/notionUtils";
import { PostListPage } from "../components/PostListPage";

interface Props {
  postSummaryList: PostSummary[];
}

export default function Home({ postSummaryList }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostListPage postSummaryList={postSummaryList} />
    </>
  );
}

export async function getStaticProps() {
  const notionPageList = await fetchNotionPageList();
  const postSummaryList =
    convertNotionPageListToPostSummaryList(notionPageList);

  return {
    props: {
      postSummaryList,
    },
  };
}
