import Head from "next/head";
import { Inter } from "@next/font/google";
import { PostSummary } from "../types";
import { fetchNotionPageList } from "../services/notionApi";
import { convertNotionPageListToPostSummaryList } from "../utils/notionUtils";
import { PostListPageHeader } from "../components/PostListPageHeader";
import { PostLink } from "../components/PostLink";

const inter = Inter({ subsets: ["latin"] });

interface Props {
  postSummaryList: PostSummary[];
}

export default function Home({ postSummaryList }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostListPageHeader />
      <div>
        {postSummaryList.map((postSummary) => {
          return <PostLink postSummary={postSummary} key={postSummary.id} />;
        })}
      </div>
    </>
  );
}

export async function getStaticProps() {
  const notionPageList = await fetchNotionPageList();
  const postSummaryList =
    convertNotionPageListToPostSummaryList(notionPageList);

  return {
    props: {
      postSummaryList,
    },
  };
}
