import Head from 'next/head'
import { Inter } from '@next/font/google'
import { PostSummary } from '../types'
import Link from 'next/link'
import { fetchNotionPageList } from '../services/notionApi'
import { convertNotionPageListToPostSummaryList } from '../utils/notionUtils'
import { PostListPageHeader } from '../components/PostListPageHeader'

const inter = Inter({ subsets: ['latin'] })

interface Props {
  postSummaryList: PostSummary[] 
}

export default function Home({postSummaryList}: Props) {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostListPageHeader />
      <div>
        {postSummaryList.map((postSummary) => {
          return <div key={postSummary.id}>
          <Link  href={`/post/${postSummary.pathname}`}>{postSummary.title}</Link>
          </div>
        })}
      </div>
    </>
  )
}


export async function getStaticProps () {
  const notionPageList = await fetchNotionPageList();
  const postSummaryList = convertNotionPageListToPostSummaryList(notionPageList);

  return {
    props: {
      postSummaryList,
    }
  }
}